[build]
  # Build command
  command = "npm run build"
  
  # Directory to publish
  publish = "dist"

  # Use Netlify's default base directory (root of repo)
  base = "/"

[build.environment]
  # Use Node 20 LTS for better ES module + polyfill support
  NODE_VERSION = "20"

  # Explicitly set the Netlify build image to Jammy (Ubuntu 22.04)
  NETLIFY_BUILD_IMAGE = "jammy"

# Optional: caching to speed up builds
[cache]
  paths = [
    "node_modules/**/*",
    ".vite/**/*"
  ]

# Optional: redirect all 404s to index.html (for Vue router history mode)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

# Better font loading
[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
